spring:
  datasource:
    url: jdbc:mysql://localhost:3306/form
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
